title: Things They Don't Teach You
description: Things I've learned along the way.  Typically technology related content.
timezone: America/New_York
remote_theme: pmarsceill/just-the-docs
search_enabled: true
