title: Things They Don't Teach You
description: Things I've learned along the way.  Typically technology related content.
timezone: America/New_York
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
search_enabled: true

footer_content: "Doug Byrd"

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

